import { useEffect, useState } from "react";
import { Trophy, Download, ArrowRight, CheckCircle, Share2, BookOpen, Zap, Star } from "lucide-react";
import WhatNext from "./WhatNext";

const COMP_KEY = "mentorai_completions";

function saveCompletion(goal, level, date) {
  const list = JSON.parse(localStorage.getItem(COMP_KEY) || "[]");
  if (!list.find(c => c.goal === goal)) {
    list.unshift({ goal, level, date, completedAt: Date.now() });
    localStorage.setItem(COMP_KEY, JSON.stringify(list.slice(0, 20)));
  }
}

function generateCertificate(goal, level, date) {
  const lines = [
    "╔══════════════════════════════════════════════════════╗",
    "║                                                      ║",
    "║           🎓  CERTIFICATE OF COMPLETION  🎓         ║",
    "║                                                      ║",
    "║                   MentorAI Platform                  ║",
    "║                                                      ║",
    "║  This certifies the successful completion of:        ║",
    "║                                                      ║",
    `║  Course: ${goal.padEnd(43)}                          ║`,
    `║  Level:  ${level.padEnd(43)}                         ║`,
    `║  Date:   ${date.padEnd(43)}                          ║`,
    "║                                                      ║",
    "║  30-Day Learning Plan — All Days Completed✅        ║",
    "║                                                      ║",
    "║  Skills demonstrated:                                ║",
    "║  • Consistent daily learning                         ║",
    "║  • Concept understanding                             ║",
    "║  • Hands-on practice                                 ║",
    "║  • Real-world application                            ║",
    "║                                                      ║",
    "╚══════════════════════════════════════════════════════╝",
    "",
    "Generated by MentorAI — Your Personal AI Learning Mentor",
  ];
  const blob = new Blob([lines.join("\n")], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `MentorAI_Certificate_${goal.replace(/\s+/g, "_")}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

const SKILLS = [
  { icon: <Zap size={13} />,       text: "Daily learning consistency" },
  { icon: <BookOpen size={13} />,  text: "Concept understanding" },
  { icon: <CheckCircle size={13} />, text: "Hands-on practice" },
  { icon: <Star size={13} />,      text: "Real-world application" },
  { icon: <Trophy size={13} />,    text: "Self-revision habits" },
];

export default function CompletionScreen({ goal, level, onStartNext, onDismiss, recentTopics = [], weakAreas = [], userLevel = 1 }) {
  const date = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  const [shared, setShared] = useState(false);

  useEffect(() => { saveCompletion(goal, level, date); }, []);

  const handleShare = () => {
    const text = `🎓 I just completed "${goal}" on MentorAI!\n\nLevel: ${level} · Date: ${date}\n\nLearn anything at mentorai.app`;
    if (navigator.share) {
      navigator.share({ title: "Course Completed!", text });
    } else {
      navigator.clipboard.writeText(text);
      setShared(true);
      setTimeout(() => setShared(false), 2000);
    }
  };

  return (
    <div className="cs-overlay">
      <div className="cs-card">

        {/* Glow ring + trophy icon */}
        <div className="cs-icon-wrap">
          <div className="cs-icon-ring" />
          <div className="cs-icon"><Trophy size={32} /></div>
        </div>

        {/* Badge */}
        <div className="cs-badge">🎉 Course Completed</div>

        {/* Title */}
        <h2 className="cs-title">You did it!</h2>
        <p className="cs-course-name">{goal}</p>
        <p className="cs-subtitle">You completed all 30 days of your personalized learning plan. That's a real achievement.</p>

        {/* Stats row */}
        <div className="cs-stats">
          <div className="cs-stat">
            <span className="cs-stat-val">30/30</span>
            <span className="cs-stat-label">Days Done</span>
          </div>
          <div className="cs-stat-divider" />
          <div className="cs-stat">
            <span className="cs-stat-val" style={{ textTransform: "capitalize" }}>{level}</span>
            <span className="cs-stat-label">Level</span>
          </div>
          <div className="cs-stat-divider" />
          <div className="cs-stat">
            <span className="cs-stat-val">100%</span>
            <span className="cs-stat-label">Complete</span>
          </div>
        </div>

        {/* Date */}
        <div className="cs-date">Completed on {date}</div>

        {/* Skills */}
        <div className="cs-skills">
          <div className="cs-skills-label">Skills Gained</div>
          <div className="cs-skills-list">
            {SKILLS.map((s, i) => (
              <div key={i} className="cs-skill-row">
                <span className="cs-skill-icon">{s.icon}</span>
                <span className="cs-skill-text">{s.text}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Actions */}
        <div className="cs-actions">
          <button className="cs-btn-primary" onClick={onStartNext}>
            <ArrowRight size={16} /> Start Next Goal
          </button>
          <button className="cs-btn-secondary" onClick={() => generateCertificate(goal, level, date)}>
            <Download size={15} /> Download Certificate
          </button>
          <button className="cs-btn-ghost" onClick={handleShare}>
            <Share2 size={15} /> {shared ? "Copied!" : "Share Achievement"}
          </button>
        </div>

        <button className="cs-dismiss" onClick={onDismiss}>
          Review course →
        </button>

        {/* What's Next */}
        <WhatNext
          recentTopics={[goal, ...recentTopics]}
          weakAreas={weakAreas}
          userLevel={userLevel}
          trigger="completion"
          compact
          onAction={({ page }) => { onDismiss?.(); }}
        />
      </div>
    </div>
  );
}
