services:
  - type: web
    name: learnai-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
  